name: "Espressif IoT Development Framework (ESP-IDF)"
description: "This action build your firmware for ESP32 directly in GitHub using Espressif ESP-IDF Docker image."
branding:
  color: red
  icon: wifi
inputs:
  target:
    description: 'Defines the type of ESP32 to build for, supported types: esp32, esp32s2, esp32s3, esp32c3. When not specified the default is esp32.'
    default: 'esp32'
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
